"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z^49v+qk$@d@$qzj616t(6vajxih)#7j!inli@p2a8dl)&$$cb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'donations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'donations_db',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
]
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

FRONTEND_URL = 'http://localhost:4200'



# Payment Settings
PAYPAL_MODE = 'sandbox'  # Change to 'live' for production
PAYPAL_CLIENT_ID = 'Aal-7wFMNZvGlx8oyjEek6MJH1I7sFgah6lbIy1TIhExDD8N3XQeafOvaMc88FiY0MT6wF5QCH9A4Ozr'
PAYPAL_CLIENT_SECRET = 'EDxqc9eRInkzVOdWBkxe1DWLDe6ZGuINalNwbJ6rNadUD_0_OYMNBPJ6fS8bbXPDVxm8a9PSz6xAWzNO'
STRIPE_SECRET_KEY = 'sk_test_51Qo5xF012dS7IRFKTBUuUau1o3dWFvkhpJgky99ahNKJ3HOHs7CDqlLl86foJWWU9V6gSiHLyTNmPZRKD04yotV500aKxG0YQN'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51Qo5xF012dS7IRFKZvm0PKkDIBFSEgfLcPLbPZ3lXr5u7BBw9XBa0yDD70znRXUQynDIj3IhUW3geP67BGkKbhu400z1wCQHtb'

# Organization Settings
ORGANIZATION_NAME = 'naba'
FRONTEND_URL = 'http://localhost:4200'

# Payment Plan IDs
PAYPAL_PLAN_IDS = {
    'monthly_100': 'P-9H666951GE1171120M67CJ7A',
    'yearly_1000': 'P-0VD902653S6829239M67QVNI',
}

STRIPE_PRICE_IDS = {
    'monthly_100': 'price_1QyvLY012dS7IRFKB7leisoJ',
    'yearly_1000': 'price_1QyvMf012dS7IRFKRS7rh9Xw',
}
STRIPE_API_VERSION = '2023-10-16'
STRIPE_PRODUCT_ID = 'prod_RsgiMpOtiOfpUQ'
