# Generated by Django 5.1.6 on 2025-03-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cause',
        ),
        migrations.CreateModel(
            name='DonationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.cause')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_details', to='donations.donation')),
            ],
        ),
    ]
