# Generated by Django 5.1.6 on 2025-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_cause_amount_remove_cause_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
