# Generated by Django 5.1.6 on 2025-03-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('one-time', 'One-time'), ('regular', 'Regular')], max_length=10),
        ),
    ]
