# Generated by Django 5.1.6 on 2025-03-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='account_holder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
