# Generated by Django 5.1.6 on 2025-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donor_account_holder_donor_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='ip_address',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
