# Generated by Django 5.1.6 on 2025-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donor_ip_address_donor_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
