# Generated by Django 5.1.6 on 2025-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donor_ip_address_alter_donor_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='donation',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
